### ISSUE TITLE
Error when trying to export a source version

### ISSUE THREAD

**Issue by fefonb** [OpenConceptLab/ocl_issues#1716]
When trying to export a version of any resource available in the OCL base, the system returns the message: could not download csv.

The version of OCL we are using is:

web: 2.1.60-dev
dev: 2.2.71-dev

![error export ocl 1](https://github.com/OpenConceptLab/ocl_issues/assets/121242947/312b430c-d256-4986-bdb2-3fa3e185579a)
![error export ocl 2](https://github.com/OpenConceptLab/ocl_issues/assets/121242947/bf580022-1624-433c-8da8-0359678d1307)

**Comment by jamlung-ri** [comment]
Hi @fefonb, thanks for submitting this ticket! I will need @snyaggarwal to help us with some of the more technical details here but as a general recommendation, it is good to save a version of your source before downloading any export files, rather than downloading from the HEAD version. 

Could you tell me if this error still occurs when exporting in any of the three formats when downloading a non-HEAD version of your content? See image below for the three format options that I am talking about: 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/f771af53-c5f3-4de9-80e7-853391c85eab)

**Comment by italomacedo** [comment]
@fefonb 

It might be related with the Bucket configuration. Check this out.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/oclapi2/core/common/mixins.py", line 674, in get
    if version.has_export():
  File "/oclapi2/core/common/models.py", line 820, in has_export
    return service.has_path(self.generic_export_path(suffix=None))
  File "/oclapi2/core/common/services.py", line 92, in has_path
    return len(cls.__fetch_keys(prefix, delimiter)) > 0
  File "/oclapi2/core/common/services.py", line 192, in __fetch_keys
    objects = s3_resource.meta.client.list_objects(Bucket=settings.AWS_STORAGE_BUCKET_NAME, Prefix=prefix)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.10/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by snyaggarwal** [comment]
@italomacedo Yep looks like the error is coming from S3 Service. Exports needs a place to stay which is S3 as default. You will need to configure S3 credentials as mentioned here -- https://github.com/OpenConceptLab/oclapi2/blob/master/docker-compose.yml#L48

**Comment by fefonb** [comment]
@snyaggarwal  @jamlung-ri @italomacedo 

Thank you very much for your brief support. We forwarded the request to configure the S3 service internally to reestablish this functionality.

Any news, I'll get in touch.

Thank you very much
