### ISSUE TITLE
Fix overwriting ConceptMap version

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#1922]
ConceptMap throws an error when trying to overwrite an exisiting version:

```
Internal Server Error: /users/ocladmin/ConceptMap/sc-research-subject-status/
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
api-1  |     return self.cursor.execute(sql, params)
api-1  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "user_source_unique"
api-1  | DETAIL:  Key (mnemonic, version, user_id)=(sc-research-subject-status, 4.0.1, 1) already exists.
api-1  | 
api-1  | 
api-1  | The above exception was the direct cause of the following exception:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
api-1  |     response = get_response(request)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/code/core/common/mixins.py", line 421, in put
api-1  |     return self.update(request)
api-1  |   File "/code/core/common/mixins.py", line 439, in update
api-1  |     self.object = serializer.save(**save_kwargs)
api-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
api-1  |     self.instance = self.update(self.instance, validated_data)
api-1  |   File "/code/core/concept_maps/serializers.py", line 228, in update
api-1  |     errors = Source.persist_new_version(source, user)
api-1  |   File "/code/core/common/models.py", line 720, in persist_new_version
api-1  |     obj.save(**kwargs)
api-1  |   File "/code/core/sources/models.py", line 408, in save
api-1  |     super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
api-1  |     self.save_base(
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
api-1  |     updated = self._save_table(
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
api-1  |     results = self._do_insert(
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
api-1  |     return manager._insert(
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
api-1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
api-1  |     cursor.execute(sql, params)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
api-1  |     return super().execute(sql, params)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
api-1  |     return self._execute_with_wrappers(
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
api-1  |     return executor(sql, params, many, context)
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
api-1  |     with self.db.wrap_database_errors:
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
api-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
api-1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
api-1  |     return self.cursor.execute(sql, params)
api-1  | django.db.utils.IntegrityError: duplicate key value violates unique constraint "user_source_unique"
api-1  | DETAIL:  Key (mnemonic, version, user_id)=(sc-research-subject-status, 4.0.1, 1) already exists.
```

**Comment by paynejd** [comment]
**FHIR Service Backlog Cleanup (March 2026)**

This issue is being closed as part of a systematic review of the OCL FHIR Service backlog. The content and context of this issue has been captured in the [FHIR Service Knowledge Base](https://github.com/OpenConceptLab/ocl_issues/wiki) and synthesis report.

If this work is still needed, it will be re-scoped in a fresh ticket with updated context. Please reopen or create a new issue if you believe this is still actively relevant.
