### ISSUE TITLE
ocl_web dependencies pulling in a version of django-appconf that doesn't support python2

### ISSUE THREAD

**Issue by Karuhanga** [OpenConceptLab/ocl_issues#219]
```
web_1               | Validating models...
web_1               | 
web_1               | >> Unhandled exception in thread started by
web_1               | >> <function wrapper at 0x7fd720a03b18>
web_1               | >> Traceback (most recent call last):
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
web_1               | >>     fn(*args, **kwargs)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 101, in inner_run
web_1               | >>     self.validate(display_num_errors=True)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
web_1               | >>     num_errors = get_validation_errors(s, app)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
web_1               | >>     for (app_name, error) in get_app_errors().items():
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
web_1               | >>     self._populate()
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in populate
web_1               | >>     self.load_app(app_name, True)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
web_1               | >>     models = import_module('%s.models' % app_name)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
web_1               | >>     __import__(name)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/avatar/models.py", line 14, in <module>
web_1               | >>     from avatar.conf import settings
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/avatar/conf.py", line 4, in <module>
web_1               | >>     from appconf import AppConf
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/appconf/__init_.py", line 1, in <module>
web_1               | >>     from .base import AppConf  # noqa
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/appconf/base.py", line 107
web_1               | >>     class AppConf(metaclass=AppConfMetaClass):
web_1               | >>                            ^
web_1               | >> SyntaxError: invalid syntax
```

**Comment by Karuhanga** [comment]
```
web_1               | Validating models...
web_1               | 
web_1               | >> Unhandled exception in thread started by
web_1               | >> <function wrapper at 0x7fd720a03b18>
web_1               | >> Traceback (most recent call last):
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
web_1               | >>     fn(*args, **kwargs)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 101, in inner_run
web_1               | >>     self.validate(display_num_errors=True)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
web_1               | >>     num_errors = get_validation_errors(s, app)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
web_1               | >>     for (app_name, error) in get_app_errors().items():
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
web_1               | >>     self._populate()
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in populate
web_1               | >>     self.load_app(app_name, True)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
web_1               | >>     models = import_module('%s.models' % app_name)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
web_1               | >>     __import__(name)
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/avatar/models.py", line 14, in <module>
web_1               | >>     from avatar.conf import settings
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/avatar/conf.py", line 4, in <module>
web_1               | >>     from appconf import AppConf
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/appconf/__init_.py", line 1, in <module>
web_1               | >>     from .base import AppConf  # noqa
web_1               | >>   File "/usr/local/lib/python2.7/site-packages/appconf/base.py", line 107
web_1               | >>     class AppConf(metaclass=AppConfMetaClass):
web_1               | >>                            ^
web_1               | >> SyntaxError: invalid syntax
```

**Comment by Karuhanga** [comment]
Fixed by https://github.com/OpenConceptLab/ocl_web/pull/341.
