### ISSUE TITLE
oclapi2 error with header INCLUDEFACETS in oclweb2

### ISSUE THREAD

**Issue by janol77** [OpenConceptLab/ocl_issues#694]
In my local deploy(docker-compose up -d), when I want to list the default concepts with the oclweb2, in a clean installation. I have the following error:

***Request:***
```bash 
curl 'http://127.0.0.1:8000/concepts/?q=&page=1&exact_match=off&limit=25&includeRetired=false&verbose=false&sortDesc=last_update' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'Accept: application/json' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'INCLUDEFACETS: true' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:4000' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:4000/' \
  -H 'Accept-Language: es-419,es;q=0.9,es-US;q=0.8,en;q=0.7' \
  --compressed
```
***Response:***
```text
RequestError at /concepts/
RequestError(400, 'search_phase_execution_exception', 'Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory.')

Request Method: GET
Request URL: http://127.0.0.1:8000/concepts/?q=&page=1&exact_match=off&limit=25&includeRetired=false&verbose=false&sortDesc=last_update
Django Version: 3.1.6
Python Executable: /usr/local/bin/python
Python Version: 3.8.3
Python Path: ['/code', '/code', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/site-packages']
Server time: Mon, 05 Apr 2021 16:53:06 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'drf_yasg',
 'django_elasticsearch_dsl',
 'corsheaders',
 'ordered_model',
 'health_check',
 'health_check.db',
 'health_check.contrib.redis',
 'core.common.apps.CommonConfig',
 'core.users',
 'core.orgs',
 'core.sources.apps.SourceConfig',
 'core.collections',
 'core.concepts',
 'core.mappings',
 'core.importers',
 'core.pins',
 'core.client_configs',
 'core.v1_importers']
Installed Middleware:
['django.middleware.gzip.GZipMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'core.middlewares.middlewares.FixMalformedLimitParamMiddleware',
 'core.middlewares.middlewares.RequestLogMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/core/concepts/views.py", line 72, in get
    return self.list(request, *args, **kwargs)
  File "/code/core/common/mixins.py", line 138, in list
    data = dict(results=result_dict, facets=dict(fields=self.get_facets()))
  File "/code/core/common/views.py", line 285, in get_facets
    facets = self.facet_class(  # pylint: disable=not-callable
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/faceted_search.py", line 423, in execute
    r = self._s.execute()
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/search.py", line 715, in execute
    self, es.search(index=self._index, body=self.to_dict(), **self._params)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1662, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(

Exception Type: RequestError at /concepts/
Exception Value: RequestError(400, 'search_phase_execution_exception', 'Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [datatype] in order to load field data by uninverting the inverted index. Note that this can use significant memory.')
Request information:
USER: AnonymousUser

GET:
q = ''
page = '1'
exact_match = 'off'
limit = '25'
includeRetired = 'false'
verbose = 'false'
sortDesc = 'last_update'

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```
Can anyone tell me if I miss something, may be param or step with my local deploy?
thanks

**Comment by snyaggarwal** [comment]
Can you run `docker exec -it oclapi2_api_1  python manage.py search_index --rebuild -f  --parallel` and then try the same API request.

**Comment by janol77** [comment]
Thanks, rebuild the index solve this
