### ISSUE TITLE
openhim dev.ohie.datim.org is down

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#775]
Log for openhim restart
```
Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/test.ohie.datim.org/fullchain.pem'
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at Object.fs.openSync (fs.js:646:18)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at Object.fs.readFileSync (fs.js:551:33)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at _keystore.KeystoreModel.findOne (/usr/lib/openhim-core/lib/server.js:573:29)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at model.Query.<anonymous> (/usr/lib/openhim-core/node_modules/mongoose/lib/model.js:4093:16)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at /usr/lib/openhim-core/node_modules/kareem/index.js:273:21
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at /usr/lib/openhim-core/node_modules/kareem/index.js:131:16
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at _combinedTickCallback (internal/process/next_tick.js:132:7)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: at process._tickCallback (internal/process/next_tick.js:181:9)
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: 2021-05-25T12:45:56.384Z - warn: [master] worker 15339 died
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: (node:15266) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
May 25 12:45:56 dev.ohie.datim.org openhim-core[15256]: 2021-05-25T12:45:56.459Z - info: [master] worker with pid 15362 is online
```

**Comment by maurya** [comment]
Settings in `/usr/lib/openhim-core/config/default.json` are configured to `test.ohie.datim.org`. Updating that to `dev.ohie.datim.org` and restarting openhim-core fixed the issue.

**Comment by maurya** [comment]
I was guessing the cert renewal script that Hiwot created might have the test.ohie.datim.org settings. But, that wouldn't change this file. So updated guess - the server was  recently updated/deployed and those deployments had test.ohie.datim.org settings
But not a complete update/deployment, that would mess with a lot of other files. Just openhim-core or openhim-console update/deployment
