### ISSUE TITLE
openMRS standalone Unable to import from subscription server

### ISSUE THREAD

**Issue by GodswillOnuoha** [OpenConceptLab/ocl_issues#92]
I installed the openMRS stand alone, installed the OCL module and configured it using subscription URL from https://openmrs.qa.openconceptlab.org/dictionaryOverview/users/admin/collections/d3h7d3e4g6d3e4/

but I get the following error when I try to import from subscription server.

<img width="1122" alt="screenshot 2019-02-15 at 2 48 54 pm" src="https://user-images.githubusercontent.com/40201026/52860831-e57ee280-3130-11e9-95fe-99d016226778.png">

**Comment by rkorytkowski** [comment]
Could you please try using a URL without a version number i.e. https://qa.openconceptlab.org/users/admin/collections/d3h7d3e4g6d3e4/ ?

**Comment by samdiano** [comment]
After removing the version number, the error changes from "NOT FOUND" to "Errors found"
![image](https://user-images.githubusercontent.com/27571135/53566858-c4b98280-3b5d-11e9-93de-692ded187fb6.png)

**Comment by Mrshinezee** [comment]
We will want to know If you have a fix to that or if you know the source of the error @rkorytkowski

**Comment by Karuhanga** [comment]
@rkorytkowski We've managed to narrow down the issue to only custom concepts, for example importing a dictionary that has only concepts from other sources e.g CIEL is successful. Importing dictionaries with custom concepts fails.

**Comment by rkorytkowski** [comment]
Please click the date and to open up the import and see what errors have been found.

If there's no relevant information there, please run the import and share here OpenMRS server logs.

**Comment by Karuhanga** [comment]
#### The logs;
```INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,102| In method ImportService.updateReleaseVersion. Arguments: Import=org.openmrs.module.openconceptlab.Import@27c, String=2, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:40,115| Exiting method updateReleaseVersion
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,118| In method ImportService.updateOclDateStarted. Arguments: Import=org.openmrs.module.openconceptlab.Import@27c, Date=Thu Apr 25 14:51:31 EAT 2019, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:40,120| Exiting method updateOclDateStarted
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,125| In method ImportService.updateSubscriptionUrl. Arguments: Import=org.openmrs.module.openconceptlab.Import@27c, String=https://api.demo.openconceptlab.org/users/admin/collections/M, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:40,128| Exiting method updateSubscriptionUrl
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,569| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:40,893| Exiting method saveConcept
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,905| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:40,943| Exiting method saveConcept
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:40,957| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:41,001| Exiting method saveConcept
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:41,010| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:41,051| Exiting method saveConcept
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:41,062| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:41,100| Exiting method saveConcept
ERROR - ImportTask$1.run(77) |2019-04-25 14:51:41,105| Failed to import concept org.openmrs.module.openconceptlab.client.OclConcept@25786f98[externalId=<null>]
org.openmrs.module.openconceptlab.importer.ImportException: Cannot create concept https://api.demo.openconceptlab.org/users/admin/sources/M/concepts/db7900b1-aabf-4ca8-bf7a-080135b6a889/5cc1958fae2d620053c9f2fc/
	at org.openmrs.module.openconceptlab.importer.Saver.saveConcept(Saver.java:105)
	at org.openmrs.module.openconceptlab.importer.ImportTask$1.run(ImportTask.java:73)
	at org.openmrs.api.context.Daemon$5.run(Daemon.java:286)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.openmrs.module.openconceptlab.CacheService.getConceptByUuid(CacheService.java:118)
	at org.openmrs.module.openconceptlab.importer.Saver.toConcept(Saver.java:174)
	at org.openmrs.module.openconceptlab.importer.Saver.saveConcept(Saver.java:103)
	... 2 more
ERROR - ImportTask$1.run(77) |2019-04-25 14:51:41,113| Failed to import concept org.openmrs.module.openconceptlab.client.OclConcept@5509f181[externalId=<null>]
org.openmrs.module.openconceptlab.importer.ImportException: Cannot create concept https://api.demo.openconceptlab.org/users/admin/sources/M/concepts/9c4dece3-6d69-435b-a9ca-c37c4f3f3d6e/5cc19ef0ae2d620053c9f32c/
	at org.openmrs.module.openconceptlab.importer.Saver.saveConcept(Saver.java:105)
	at org.openmrs.module.openconceptlab.importer.ImportTask$1.run(ImportTask.java:73)
	at org.openmrs.api.context.Daemon$5.run(Daemon.java:286)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.openmrs.module.openconceptlab.CacheService.getConceptByUuid(CacheService.java:118)
	at org.openmrs.module.openconceptlab.importer.Saver.toConcept(Saver.java:174)
	at org.openmrs.module.openconceptlab.importer.Saver.saveConcept(Saver.java:103)
	... 2 more
INFO - LoggingAdvice.invoke(115) |2019-04-25 14:51:41,117| In method ImportService.saveItems. Arguments: Iterable=[org.openmrs.module.openconceptlab.Item@15c4c81e[itemId=<null>,uuid=82372AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA], org.openmrs.module.openconceptlab.Item@6300dd3a[itemId=<null>,uuid=82389AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA], org.openmrs.module.openconceptlab.Item@c7d3669[itemId=<null>,uuid=82390AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA], org.openmrs.module.openconceptlab.Item@2fc1cd9f[itemId=<null>,uuid=82392AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA], org.openmrs.module.openconceptlab.Item@1c766441[itemId=<null>,uuid=82393AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA], org.openmrs.module.openconceptlab.Item@79fa93f8[itemId=<null>,uuid=<null>], org.openmrs.module.openconceptlab.Item@1cd13cd0[itemId=<null>,uuid=<null>]], 
INFO - LoggingAdvice.invoke(155) |2019-04-25 14:51:41,127| Exiting method saveItems
```

**Comment by Karuhanga** [comment]
> @rkorytkowski We've managed to narrow down the issue to only custom concepts, for example importing a dictionary that has only concepts from other sources e.g CIEL is successful. Importing dictionaries with custom concepts fails.

[This ticket](https://issues.openmrs.org/browse/OCLM-65) contains an [updated OCL subscription module](https://issues.openmrs.org/secure/attachment/54995/openconceptlab-1.2.4-SNAPSHOT.omod) that addresses this particular issue.

**Comment by paynejd** [comment]
This has been resolved -- closing out
