### ISSUE TITLE
MultipleObjectsReturned for get() on Collections (production)

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_issues#969]
I've spotted the following error in production logs:

2021-09-13T00:09:10.363+02:00	Internal Server Error: /collections/NCoD-Extended/summary/

2021-09-13T00:09:10.363+02:00	Traceback (most recent call last):

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

2021-09-13T00:09:10.363+02:00	response = get_response(request)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

2021-09-13T00:09:10.363+02:00	response = wrapped_callback(request, *callback_args, **callback_kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

2021-09-13T00:09:10.363+02:00	return view_func(*args, **kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view

2021-09-13T00:09:10.363+02:00	return self.dispatch(request, *args, **kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch

2021-09-13T00:09:10.363+02:00	response = self.handle_exception(exc)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception

2021-09-13T00:09:10.363+02:00	self.raise_uncaught_exception(exc)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

2021-09-13T00:09:10.363+02:00	raise exc

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch

2021-09-13T00:09:10.363+02:00	response = handler(request, *args, **kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 208, in get

2021-09-13T00:09:10.363+02:00	return self.retrieve(request, *args, **kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 54, in retrieve

2021-09-13T00:09:10.363+02:00	instance = self.get_object()

2021-09-13T00:09:10.363+02:00	File "/code/core/collections/views.py", line 608, in get_object

2021-09-13T00:09:10.363+02:00	instance = get_object_or_404(self.get_queryset())

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404

2021-09-13T00:09:10.363+02:00	return queryset.get(*args, **kwargs)

2021-09-13T00:09:10.363+02:00	File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 439, in get

2021-09-13T00:09:10.363+02:00	raise self.model.MultipleObjectsReturned(

2021-09-13T00:09:10.363+02:00	core.collections.models.Collection.MultipleObjectsReturned: get() returned more than one Collection -- it returned 3!

@snyaggarwal any thoughts?

**Comment by snyaggarwal** [comment]
@rkorytkowski This is a bad queryset expression. I will work on this one.

**Comment by snyaggarwal** [comment]
@rkorytkowski `/collections/NCoD-Extended/summary/` is a bad REST URL. It should be returning 404.
The correct one is `/orgs/something/collections/NCoD-Extended/summary/`. I did work on this last week to not support these. That work is captured as part of #971
